///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("77ea5a2c-5348-4cc2-a256-d975bb1aefe0")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("77ea5a2c-5348-4cc2-a256-d975bb1aefe0")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "77ea5a2c-5348-4cc2-a256-d975bb1aefe0", ".\\RepositoryImages\\MyTestRepository77ea5a2c.rximgres")
        {
            _applicationundertest = new MyTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("77ea5a2c-5348-4cc2-a256-d975bb1aefe0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("ce52d1c8-263b-437e-98de-ac315cdd86a8")]
        public virtual MyTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("ce52d1c8-263b-437e-98de-ac315cdd86a8")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _epicsadfaceusernameisrequiredInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.saucedemo.com']", parentFolder, 30000, null, false, "ce52d1c8-263b-437e-98de-ac315cdd86a8", "")
            {
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[#'user-name']", ".//input[#'user-name']", 30000, null, "b3808437-69f6-497b-8c0b-c7448c57fe21");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", ".//input[#'password']", 30000, null, "e0decc90-f72b-4f0a-a2ba-efd57ed7a7f4");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//input[#'login-button']", ".//input[#'login-button']", 30000, null, "0bead7ec-169e-45ba-ab89-4c4ea39acbc6");
                _epicsadfaceusernameisrequiredInfo = new RepoItemInfo(this, "EpicSadfaceUsernameIsRequired", ".//div[#'login_button_container']/?/?/form[@action='https://www.saucedemo.com/v1/index.html']/h3[@innertext>'Epic sadface: Username is']", ".//div[#'login_button_container']//h3[@innertext>'Epic sadface: Username is']", 30000, null, "cf6ec188-7ca9-4b4e-b94d-c3923a28febd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ce52d1c8-263b-437e-98de-ac315cdd86a8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ce52d1c8-263b-437e-98de-ac315cdd86a8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("b3808437-69f6-497b-8c0b-c7448c57fe21")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("b3808437-69f6-497b-8c0b-c7448c57fe21")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("e0decc90-f72b-4f0a-a2ba-efd57ed7a7f4")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("e0decc90-f72b-4f0a-a2ba-efd57ed7a7f4")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("0bead7ec-169e-45ba-ab89-4c4ea39acbc6")]
            public virtual Ranorex.InputTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("0bead7ec-169e-45ba-ab89-4c4ea39acbc6")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The EpicSadfaceUsernameIsRequired item.
            /// </summary>
            [RepositoryItem("cf6ec188-7ca9-4b4e-b94d-c3923a28febd")]
            public virtual Ranorex.H3Tag EpicSadfaceUsernameIsRequired
            {
                get
                {
                    return _epicsadfaceusernameisrequiredInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The EpicSadfaceUsernameIsRequired item info.
            /// </summary>
            [RepositoryItemInfo("cf6ec188-7ca9-4b4e-b94d-c3923a28febd")]
            public virtual RepoItemInfo EpicSadfaceUsernameIsRequiredInfo
            {
                get
                {
                    return _epicsadfaceusernameisrequiredInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
