///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("baae2832-98ca-4bf4-81ed-f1d7a1154c03")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTest1RepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("baae2832-98ca-4bf4-81ed-f1d7a1154c03")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "baae2832-98ca-4bf4-81ed-f1d7a1154c03", ".\\RepositoryImages\\MyTest1Repositorybaae2832.rximgres")
        {
            _applicationundertest = new MyTest1RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new MyTest1RepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("baae2832-98ca-4bf4-81ed-f1d7a1154c03")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a6fa0063-7074-4d2b-9b7e-9ccae3c10033")]
        public virtual MyTest1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("e0f102f1-c7c9-48b4-bc22-625f4a454fb6")]
        public virtual MyTest1RepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a6fa0063-7074-4d2b-9b7e-9ccae3c10033")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.saucedemo.com']", parentFolder, 30000, null, false, "a6fa0063-7074-4d2b-9b7e-9ccae3c10033", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a6fa0063-7074-4d2b-9b7e-9ccae3c10033")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a6fa0063-7074-4d2b-9b7e-9ccae3c10033")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("e0f102f1-c7c9-48b4-bc22-625f4a454fb6")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mytest1ranorexstudio32bitInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/form[@title='']", parentFolder, 30000, null, true, "e0f102f1-c7c9-48b4-bc22-625f4a454fb6", "")
            {
                _mytest1ranorexstudio32bitInfo = new RepoItemInfo(this, "MyTest1RanorexStudio32bit", "?/?/listitem[@accessiblename>'MyTest1 - Ranorex Studio -']", "?/?/listitem[@accessiblename>'MyTest1 - Ranorex Studio -']", 30000, null, "cdf533dc-2f56-4cdd-90fc-2a75a83e4dad");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e0f102f1-c7c9-48b4-bc22-625f4a454fb6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e0f102f1-c7c9-48b4-bc22-625f4a454fb6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyTest1RanorexStudio32bit item.
            /// </summary>
            [RepositoryItem("cdf533dc-2f56-4cdd-90fc-2a75a83e4dad")]
            public virtual Ranorex.ListItem MyTest1RanorexStudio32bit
            {
                get
                {
                    return _mytest1ranorexstudio32bitInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The MyTest1RanorexStudio32bit item info.
            /// </summary>
            [RepositoryItemInfo("cdf533dc-2f56-4cdd-90fc-2a75a83e4dad")]
            public virtual RepoItemInfo MyTest1RanorexStudio32bitInfo
            {
                get
                {
                    return _mytest1ranorexstudio32bitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
