///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePassTestSuite.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEntryByUserCodeAction recording.
    /// </summary>
    [TestModule("00d7086b-8b33-4901-afda-051e48be3c55", ModuleType.Recording, 1)]
    public partial class AddEntryByUserCodeAction : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePassTestSuite.KeePassTestSuiteRepository repository.
        /// </summary>
        public static global::KeePassTestSuite.KeePassTestSuiteRepository repo = global::KeePassTestSuite.KeePassTestSuiteRepository.Instance;

        static AddEntryByUserCodeAction instance = new AddEntryByUserCodeAction();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEntryByUserCodeAction()
        {
            varTitle = "WordPressDemo";
            varUsername = "admin";
            varPassword = "demo123";
            varURL = "bitly.com/wp_demo";
            varIconIndex = "5";
            varExpires = "1 Year";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEntryByUserCodeAction Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUsername;

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("e7267f59-0be0-4eb2-83a5-3b62d60332c6")]
        public string varUsername
        {
            get { return _varUsername; }
            set { _varUsername = value; }
        }

        string _varPassword;

        /// <summary>
        /// Gets or sets the value of variable varPassword.
        /// </summary>
        [TestVariable("0237523a-474e-46a0-ba43-49a8977bc725")]
        public string varPassword
        {
            get { return _varPassword; }
            set { _varPassword = value; }
        }

        string _varURL;

        /// <summary>
        /// Gets or sets the value of variable varURL.
        /// </summary>
        [TestVariable("dab46601-f0c9-472b-a632-dd0f6eac4514")]
        public string varURL
        {
            get { return _varURL; }
            set { _varURL = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varIconIndex.
        /// </summary>
        [TestVariable("b832d535-1f07-4b07-81c7-858db28af322")]
        public string varIconIndex
        {
            get { return repo.varIconIndex; }
            set { repo.varIconIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varExpires.
        /// </summary>
        [TestVariable("20fe3344-992b-45f2-ba6d-eb12b460df90")]
        public string varExpires
        {
            get { return repo.varExpires; }
            set { repo.varExpires = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("784c5427-5da9-4308-b359-2e6b8124c417")]
        public string varTitle
        {
            get { return repo.varTitle; }
            set { repo.varTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Edit' at Center.", repo.MainForm.EditInfo, new RecordItemIndex(0));
            repo.MainForm.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.AddEntry' at Center.", repo.KeePass.AddEntryInfo, new RecordItemIndex(1));
            repo.KeePass.AddEntry.Click();
            Delay.Milliseconds(200);
            
            AddEntryWithParams(varTitle, varUsername, varPassword, "", varIconIndex, varExpires);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.ButtonOK' at Center.", repo.AddEntry.ButtonOKInfo, new RecordItemIndex(3));
            repo.AddEntry.ButtonOK.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
