///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePassTestSuite.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteGroup recording.
    /// </summary>
    [TestModule("6b502c5c-26e5-46bd-813b-9a4f90f0684d", ModuleType.Recording, 1)]
    public partial class DeleteGroup : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePassTestSuite.KeePassTestSuiteRepository repository.
        /// </summary>
        public static global::KeePassTestSuite.KeePassTestSuiteRepository repo = global::KeePassTestSuite.KeePassTestSuiteRepository.Instance;

        static DeleteGroup instance = new DeleteGroup();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteGroup()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteGroup Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varGroupName.
        /// </summary>
        [TestVariable("93799613-85ba-4c22-aeb8-f96238c3abf7")]
        public string varGroupName
        {
            get { return repo.varGroupName; }
            set { repo.varGroupName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'MainForm.Categories.CategoryRanorex' at Center.", repo.MainForm.Categories.CategoryRanorexInfo, new RecordItemIndex(0));
            repo.MainForm.Categories.CategoryRanorex.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.DeleteGroup' at Center.", repo.KeePass.DeleteGroupInfo, new RecordItemIndex(1));
            repo.KeePass.DeleteGroup.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
