///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d8add5c3-0998-41ef-8d0d-b9babd83cfdc")]
    public partial class MyTest2Repository : RepoGenBaseFolder
    {
        static MyTest2Repository instance = new MyTest2Repository();
        MyTest2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTest2RepositoryFolders.ExplorerAppFolder _explorer;
        MyTest2RepositoryFolders.TestLoginPracticeTestAutomationAppFolder _testloginpracticetestautomation;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest2Repository element repository.
        /// </summary>
        [RepositoryFolder("d8add5c3-0998-41ef-8d0d-b9babd83cfdc")]
        public static MyTest2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest2Repository() 
            : base("MyTest2Repository", "/", null, 0, false, "d8add5c3-0998-41ef-8d0d-b9babd83cfdc", ".\\RepositoryImages\\MyTest2Repositoryd8add5c3.rximgres")
        {
            _applicationundertest = new MyTest2RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new MyTest2RepositoryFolders.ExplorerAppFolder(this);
            _testloginpracticetestautomation = new MyTest2RepositoryFolders.TestLoginPracticeTestAutomationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d8add5c3-0998-41ef-8d0d-b9babd83cfdc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("16764795-c541-4999-aa9e-b697495e7f3a")]
        public virtual MyTest2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("882a8ae7-3d60-4ca7-8472-be2dc6d5d86c")]
        public virtual MyTest2RepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The TestLoginPracticeTestAutomation folder.
        /// </summary>
        [RepositoryFolder("55c9d2a9-eb39-432a-9ea3-280b7122b00e")]
        public virtual MyTest2RepositoryFolders.TestLoginPracticeTestAutomationAppFolder TestLoginPracticeTestAutomation
        {
            get { return _testloginpracticetestautomation; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("16764795-c541-4999-aa9e-b697495e7f3a")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _productsInfo;
            RepoItemInfo _applogoInfo;
            RepoItemInfo _openmenuInfo;
            RepoItemInfo _logoutsidebarlinkInfo;
            HttpsWwwSaucedemoComV1ImgLoginBInfoClass _httpswwwsaucedemocomv1imgloginbInfo;
            RepoItemInfo _epicsadfaceusernameandpassworddonInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.saucedemo.com']", parentFolder, 30000, null, false, "16764795-c541-4999-aa9e-b697495e7f3a", "")
            {
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[#'user-name']", ".//input[#'user-name']", 30000, null, "efbcf448-4c80-43bb-91bd-e05a1203f7d3");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", ".//input[#'password']", 30000, null, "349dd508-360e-4b13-b054-fba756f0dceb");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//input[#'login-button']", ".//input[#'login-button']", 30000, null, "a445b0cc-2bb6-4371-8eb0-fe1afc81d7c4");
                _productsInfo = new RepoItemInfo(this, "Products", ".//div[#'inventory_filter_container']/div[@innertext='Products']", ".//div[#'inventory_filter_container']/div[@innertext='Products']", 30000, null, "a0f00ad8-7085-4c29-8840-8720f49b65f2");
                _applogoInfo = new RepoItemInfo(this, "AppLogo", ".//div[#'header_container']/?/?/div", ".//div[#'header_container']/?/?/div", 30000, null, "eccd0e91-0ae0-4773-9e08-8ac4ccf62e98");
                _openmenuInfo = new RepoItemInfo(this, "OpenMenu", ".//div[#'menu_button_container']/div/div[3]/?/?/button[@innertext='Open Menu']", ".//div[#'menu_button_container']//button[@innertext='Open Menu']", 30000, null, "87bc26de-a05f-4bf6-8073-083f6d01bd52");
                _logoutsidebarlinkInfo = new RepoItemInfo(this, "LogoutSidebarLink", ".//a[#'logout_sidebar_link']", ".//a[#'logout_sidebar_link']", 30000, null, "810cdb90-bb36-42aa-951f-55db31a75891");
                _httpswwwsaucedemocomv1imgloginbInfo = new HttpsWwwSaucedemoComV1ImgLoginBInfoClass(this);
                _epicsadfaceusernameandpassworddonInfo = new RepoItemInfo(this, "EpicSadfaceUsernameAndPasswordDoN", ".//div[#'login_button_container']/?/?/form[@action='https://www.saucedemo.com/v1/index.html']/h3[@innertext>'Epic sadface: Username and']", ".//div[#'login_button_container']//h3[@innertext>'Epic sadface: Username and']", 30000, null, "e70c6331-4aeb-424d-a029-dd18e809d3bc");
            }

            /// <summary>
            /// The HttpsWwwSaucedemoComV1ImgLoginBInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("7b6bc0ff-88b8-4af0-8195-b9b50b06eb81")]
            public class HttpsWwwSaucedemoComV1ImgLoginBInfoClass : RepoItemInfo
            {
                /// <summary>
                /// HttpsWwwSaucedemoComV1ImgLoginBInfoClass class constructor.
                /// </summary>
                public HttpsWwwSaucedemoComV1ImgLoginBInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "HttpsWwwSaucedemoComV1ImgLoginB", "body/div[2]/?/?/img[@src='https://www.saucedemo.com/v1/img/Login_Bot_graphic.png']", 30000, null, "7b6bc0ff-88b8-4af0-8195-b9b50b06eb81")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e63d4da5-dafe-4ed7-a6db-02b3fcda3f54")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e63d4da5-dafe-4ed7-a6db-02b3fcda3f54");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e63d4da5-dafe-4ed7-a6db-02b3fcda3f54")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e63d4da5-dafe-4ed7-a6db-02b3fcda3f54", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("16764795-c541-4999-aa9e-b697495e7f3a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("16764795-c541-4999-aa9e-b697495e7f3a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("efbcf448-4c80-43bb-91bd-e05a1203f7d3")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("efbcf448-4c80-43bb-91bd-e05a1203f7d3")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("349dd508-360e-4b13-b054-fba756f0dceb")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("349dd508-360e-4b13-b054-fba756f0dceb")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("a445b0cc-2bb6-4371-8eb0-fe1afc81d7c4")]
            public virtual Ranorex.InputTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("a445b0cc-2bb6-4371-8eb0-fe1afc81d7c4")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The Products item.
            /// </summary>
            [RepositoryItem("a0f00ad8-7085-4c29-8840-8720f49b65f2")]
            public virtual Ranorex.DivTag Products
            {
                get
                {
                    return _productsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Products item info.
            /// </summary>
            [RepositoryItemInfo("a0f00ad8-7085-4c29-8840-8720f49b65f2")]
            public virtual RepoItemInfo ProductsInfo
            {
                get
                {
                    return _productsInfo;
                }
            }

            /// <summary>
            /// The AppLogo item.
            /// </summary>
            [RepositoryItem("eccd0e91-0ae0-4773-9e08-8ac4ccf62e98")]
            public virtual Ranorex.DivTag AppLogo
            {
                get
                {
                    return _applogoInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AppLogo item info.
            /// </summary>
            [RepositoryItemInfo("eccd0e91-0ae0-4773-9e08-8ac4ccf62e98")]
            public virtual RepoItemInfo AppLogoInfo
            {
                get
                {
                    return _applogoInfo;
                }
            }

            /// <summary>
            /// The OpenMenu item.
            /// </summary>
            [RepositoryItem("87bc26de-a05f-4bf6-8073-083f6d01bd52")]
            public virtual Ranorex.ButtonTag OpenMenu
            {
                get
                {
                    return _openmenuInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The OpenMenu item info.
            /// </summary>
            [RepositoryItemInfo("87bc26de-a05f-4bf6-8073-083f6d01bd52")]
            public virtual RepoItemInfo OpenMenuInfo
            {
                get
                {
                    return _openmenuInfo;
                }
            }

            /// <summary>
            /// The LogoutSidebarLink item.
            /// </summary>
            [RepositoryItem("810cdb90-bb36-42aa-951f-55db31a75891")]
            public virtual Ranorex.ATag LogoutSidebarLink
            {
                get
                {
                    return _logoutsidebarlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogoutSidebarLink item info.
            /// </summary>
            [RepositoryItemInfo("810cdb90-bb36-42aa-951f-55db31a75891")]
            public virtual RepoItemInfo LogoutSidebarLinkInfo
            {
                get
                {
                    return _logoutsidebarlinkInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwSaucedemoComV1ImgLoginB item.
            /// </summary>
            [RepositoryItem("7b6bc0ff-88b8-4af0-8195-b9b50b06eb81")]
            public virtual Ranorex.ImgTag HttpsWwwSaucedemoComV1ImgLoginB
            {
                get
                {
                    return _httpswwwsaucedemocomv1imgloginbInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwSaucedemoComV1ImgLoginB item info.
            /// </summary>
            [RepositoryItemInfo("7b6bc0ff-88b8-4af0-8195-b9b50b06eb81")]
            public virtual HttpsWwwSaucedemoComV1ImgLoginBInfoClass HttpsWwwSaucedemoComV1ImgLoginBInfo
            {
                get
                {
                    return _httpswwwsaucedemocomv1imgloginbInfo;
                }
            }

            /// <summary>
            /// The EpicSadfaceUsernameAndPasswordDoN item.
            /// </summary>
            [RepositoryItem("e70c6331-4aeb-424d-a029-dd18e809d3bc")]
            public virtual Ranorex.H3Tag EpicSadfaceUsernameAndPasswordDoN
            {
                get
                {
                    return _epicsadfaceusernameandpassworddonInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The EpicSadfaceUsernameAndPasswordDoN item info.
            /// </summary>
            [RepositoryItemInfo("e70c6331-4aeb-424d-a029-dd18e809d3bc")]
            public virtual RepoItemInfo EpicSadfaceUsernameAndPasswordDoNInfo
            {
                get
                {
                    return _epicsadfaceusernameandpassworddonInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("882a8ae7-3d60-4ca7-8472-be2dc6d5d86c")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mytest2ranorexstudio32bitInfo;
            RepoItemInfo _swaglabsgooglechromeInfo;
            RepoItemInfo _testloginpracticetestautomationInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/form[@title='']", parentFolder, 30000, null, true, "882a8ae7-3d60-4ca7-8472-be2dc6d5d86c", "")
            {
                _mytest2ranorexstudio32bitInfo = new RepoItemInfo(this, "MyTest2RanorexStudio32bit", "?/?/listitem[@accessiblename>'MyTest2 - Ranorex Studio -']", "?/?/listitem[@accessiblename>'MyTest2 - Ranorex Studio -']", 30000, null, "8a18b9d0-4ef0-4a3f-9a27-7f74f852655d");
                _swaglabsgooglechromeInfo = new RepoItemInfo(this, "SwagLabsGoogleChrome", "?/?/listitem[@accessiblename='Swag Labs - Google Chrome']", "?/?/listitem[@accessiblename='Swag Labs - Google Chrome']", 30000, null, "199288d6-03d9-48a6-be42-3b196c02d518");
                _testloginpracticetestautomationInfo = new RepoItemInfo(this, "TestLoginPracticeTestAutomation", "?/?/listitem[@accessiblename>'Test Login | Practice Test']", "?/?/listitem[@accessiblename>'Test Login | Practice Test']", 30000, null, "eb281b31-92b9-4fae-a3b2-06041fa40c0c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("882a8ae7-3d60-4ca7-8472-be2dc6d5d86c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("882a8ae7-3d60-4ca7-8472-be2dc6d5d86c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyTest2RanorexStudio32bit item.
            /// </summary>
            [RepositoryItem("8a18b9d0-4ef0-4a3f-9a27-7f74f852655d")]
            public virtual Ranorex.ListItem MyTest2RanorexStudio32bit
            {
                get
                {
                    return _mytest2ranorexstudio32bitInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The MyTest2RanorexStudio32bit item info.
            /// </summary>
            [RepositoryItemInfo("8a18b9d0-4ef0-4a3f-9a27-7f74f852655d")]
            public virtual RepoItemInfo MyTest2RanorexStudio32bitInfo
            {
                get
                {
                    return _mytest2ranorexstudio32bitInfo;
                }
            }

            /// <summary>
            /// The SwagLabsGoogleChrome item.
            /// </summary>
            [RepositoryItem("199288d6-03d9-48a6-be42-3b196c02d518")]
            public virtual Ranorex.ListItem SwagLabsGoogleChrome
            {
                get
                {
                    return _swaglabsgooglechromeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SwagLabsGoogleChrome item info.
            /// </summary>
            [RepositoryItemInfo("199288d6-03d9-48a6-be42-3b196c02d518")]
            public virtual RepoItemInfo SwagLabsGoogleChromeInfo
            {
                get
                {
                    return _swaglabsgooglechromeInfo;
                }
            }

            /// <summary>
            /// The TestLoginPracticeTestAutomation item.
            /// </summary>
            [RepositoryItem("eb281b31-92b9-4fae-a3b2-06041fa40c0c")]
            public virtual Ranorex.ListItem TestLoginPracticeTestAutomation
            {
                get
                {
                    return _testloginpracticetestautomationInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The TestLoginPracticeTestAutomation item info.
            /// </summary>
            [RepositoryItemInfo("eb281b31-92b9-4fae-a3b2-06041fa40c0c")]
            public virtual RepoItemInfo TestLoginPracticeTestAutomationInfo
            {
                get
                {
                    return _testloginpracticetestautomationInfo;
                }
            }
        }

        /// <summary>
        /// The TestLoginPracticeTestAutomationAppFolder folder.
        /// </summary>
        [RepositoryFolder("55c9d2a9-eb39-432a-9ea3-280b7122b00e")]
        public partial class TestLoginPracticeTestAutomationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new TestLoginPracticeTestAutomation  folder.
            /// </summary>
            public TestLoginPracticeTestAutomationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestLoginPracticeTestAutomation", "/dom[@domain='practicetestautomation.com']", parentFolder, 30000, null, false, "55c9d2a9-eb39-432a-9ea3-280b7122b00e", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", ".//input[#'username']", 30000, null, "b174431c-bfd3-41d4-9b23-2ef107eda510");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", ".//input[#'password']", 30000, null, "e0b03cee-ca81-4c8c-9392-ce23b9757539");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//button[#'submit']", ".//button[#'submit']", 30000, null, "572977fd-9696-48ca-98aa-63dbb4f7612a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55c9d2a9-eb39-432a-9ea3-280b7122b00e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55c9d2a9-eb39-432a-9ea3-280b7122b00e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("b174431c-bfd3-41d4-9b23-2ef107eda510")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("b174431c-bfd3-41d4-9b23-2ef107eda510")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("e0b03cee-ca81-4c8c-9392-ce23b9757539")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("e0b03cee-ca81-4c8c-9392-ce23b9757539")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("572977fd-9696-48ca-98aa-63dbb4f7612a")]
            public virtual Ranorex.ButtonTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("572977fd-9696-48ca-98aa-63dbb4f7612a")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
