///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UsuarioContrasena_E recording.
    /// </summary>
    [TestModule("2154e85a-a6a3-47df-8462-c37c58a1aef6", ModuleType.Recording, 1)]
    public partial class UsuarioContrasena_E : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest2Repository repository.
        /// </summary>
        public static MyTest2Repository repo = MyTest2Repository.Instance;

        static UsuarioContrasena_E instance = new UsuarioContrasena_E();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UsuarioContrasena_E()
        {
            usuarioInvalido = "";
            contrasenainvalida = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UsuarioContrasena_E Instance
        {
            get { return instance; }
        }

#region Variables

        string _usuarioInvalido;

        /// <summary>
        /// Gets or sets the value of variable usuarioInvalido.
        /// </summary>
        [TestVariable("396f18b5-f58e-4c6c-a091-173f45e38082")]
        public string usuarioInvalido
        {
            get { return _usuarioInvalido; }
            set { _usuarioInvalido = value; }
        }

        string _contrasenainvalida;

        /// <summary>
        /// Gets or sets the value of variable contrasenainvalida.
        /// </summary>
        [TestVariable("a523033c-d479-44fc-bb73-127acb3198ef")]
        public string contrasenainvalida
        {
            get { return _contrasenainvalida; }
            set { _contrasenainvalida = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserName' at Center.", repo.ApplicationUnderTest.UserNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.UserName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$usuarioInvalido' with focus on 'ApplicationUnderTest.UserName'.", repo.ApplicationUnderTest.UserNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.UserName.PressKeys(usuarioInvalido);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Password' at 35;19.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Password.Click("35;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$contrasenainvalida' with focus on 'ApplicationUnderTest.Password'.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Password.PressKeys(contrasenainvalida);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
