///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UsuarioContrasena recording.
    /// </summary>
    [TestModule("119e2333-42e7-448f-8e7f-b29ef77703ae", ModuleType.Recording, 1)]
    public partial class UsuarioContrasena : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest2Repository repository.
        /// </summary>
        public static MyTest2Repository repo = MyTest2Repository.Instance;

        static UsuarioContrasena instance = new UsuarioContrasena();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UsuarioContrasena()
        {
            usuario = "";
            contrasena = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UsuarioContrasena Instance
        {
            get { return instance; }
        }

#region Variables

        string _usuario;

        /// <summary>
        /// Gets or sets the value of variable usuario.
        /// </summary>
        [TestVariable("331c8927-23ab-4b14-b31a-4687afb89c18")]
        public string usuario
        {
            get { return _usuario; }
            set { _usuario = value; }
        }

        string _contrasena;

        /// <summary>
        /// Gets or sets the value of variable contrasena.
        /// </summary>
        [TestVariable("5f951ef3-7717-4bd2-bfc5-aa75bd26a857")]
        public string contrasena
        {
            get { return _contrasena; }
            set { _contrasena = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestLoginPracticeTestAutomation.Username' at .47;.49.", repo.TestLoginPracticeTestAutomation.UsernameInfo, new RecordItemIndex(0));
            repo.TestLoginPracticeTestAutomation.Username.Click(".47;.49");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$usuario' with focus on 'TestLoginPracticeTestAutomation.Username'.", repo.TestLoginPracticeTestAutomation.UsernameInfo, new RecordItemIndex(1));
            repo.TestLoginPracticeTestAutomation.Username.PressKeys(usuario);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestLoginPracticeTestAutomation.Password' at 35;19.", repo.TestLoginPracticeTestAutomation.PasswordInfo, new RecordItemIndex(2));
            repo.TestLoginPracticeTestAutomation.Password.Click("35;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$contrasena' with focus on 'TestLoginPracticeTestAutomation.Password'.", repo.TestLoginPracticeTestAutomation.PasswordInfo, new RecordItemIndex(3));
            repo.TestLoginPracticeTestAutomation.Password.PressKeys(contrasena);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
