///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KeePassTestSuite
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the KeePassTestSuiteRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0e2cdd23-dd72-4d10-b662-4933e627b6fb")]
    public partial class KeePassTestSuiteRepository : RepoGenBaseFolder
    {
        static KeePassTestSuiteRepository instance = new KeePassTestSuiteRepository();
        KeePassTestSuiteRepositoryFolders.LogInAppFolder _login;
        KeePassTestSuiteRepositoryFolders.MainFormAppFolder _mainform;
        KeePassTestSuiteRepositoryFolders.KeePassAppFolder _keepass;
        KeePassTestSuiteRepositoryFolders.AddEntryAppFolder _addentry;
        KeePassTestSuiteRepositoryFolders.IconPickerAppFolder _iconpicker;
        KeePassTestSuiteRepositoryFolders.KeePass2AppFolder _keepass2;

        /// <summary>
        /// Gets the singleton class instance representing the KeePassTestSuiteRepository element repository.
        /// </summary>
        [RepositoryFolder("0e2cdd23-dd72-4d10-b662-4933e627b6fb")]
        public static KeePassTestSuiteRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public KeePassTestSuiteRepository() 
            : base("KeePassTestSuiteRepository", "/", null, 0, false, "0e2cdd23-dd72-4d10-b662-4933e627b6fb", ".\\RepositoryImages\\KeePassTestSuiteRepository0e2cdd23.rximgres")
        {
            _login = new KeePassTestSuiteRepositoryFolders.LogInAppFolder(this);
            _mainform = new KeePassTestSuiteRepositoryFolders.MainFormAppFolder(this);
            _keepass = new KeePassTestSuiteRepositoryFolders.KeePassAppFolder(this);
            _addentry = new KeePassTestSuiteRepositoryFolders.AddEntryAppFolder(this);
            _iconpicker = new KeePassTestSuiteRepositoryFolders.IconPickerAppFolder(this);
            _keepass2 = new KeePassTestSuiteRepositoryFolders.KeePass2AppFolder(this);
        }

#region Variables

        string _varExpires = "1 Year";

        /// <summary>
        /// Gets or sets the value of variable varExpires.
        /// </summary>
        [TestVariable("7230104a-3274-4758-9034-592ec4e96356")]
        public string varExpires
        {
            get { return _varExpires; }
            set { _varExpires = value; }
        }

        string _varIconIndex = "1";

        /// <summary>
        /// Gets or sets the value of variable varIconIndex.
        /// </summary>
        [TestVariable("c48df24c-030a-4a73-997a-4632b57b8423")]
        public string varIconIndex
        {
            get { return _varIconIndex; }
            set { _varIconIndex = value; }
        }

        string _varTitle = "WordPress";

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("64154ab2-5fe8-42d9-8fd7-c58f64ade382")]
        public string varTitle
        {
            get { return _varTitle; }
            set { _varTitle = value; }
        }

        string _varGroupName = "Ranorex";

        /// <summary>
        /// Gets or sets the value of variable varGroupName.
        /// </summary>
        [TestVariable("93799613-85ba-4c22-aeb8-f96238c3abf7")]
        public string varGroupName
        {
            get { return _varGroupName; }
            set { _varGroupName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0e2cdd23-dd72-4d10-b662-4933e627b6fb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LogIn folder.
        /// </summary>
        [RepositoryFolder("93269426-4e2d-4251-b500-04dc1535117a")]
        public virtual KeePassTestSuiteRepositoryFolders.LogInAppFolder LogIn
        {
            get { return _login; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("ad974edd-95b8-413f-81d1-04a1248ba54a")]
        public virtual KeePassTestSuiteRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("7f6a0acc-bda2-4507-8279-5c2acdc4ba2a")]
        public virtual KeePassTestSuiteRepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }

        /// <summary>
        /// The AddEntry folder.
        /// </summary>
        [RepositoryFolder("b88782a2-88f5-440d-8c3d-5d21e45f1f1b")]
        public virtual KeePassTestSuiteRepositoryFolders.AddEntryAppFolder AddEntry
        {
            get { return _addentry; }
        }

        /// <summary>
        /// The IconPicker folder.
        /// </summary>
        [RepositoryFolder("f165a7fa-478e-496b-9e0c-0d6723f3dc83")]
        public virtual KeePassTestSuiteRepositoryFolders.IconPickerAppFolder IconPicker
        {
            get { return _iconpicker; }
        }

        /// <summary>
        /// The KeePass2 folder.
        /// </summary>
        [RepositoryFolder("eba40eb0-9836-4cdd-950b-f45c7746145d")]
        public virtual KeePassTestSuiteRepositoryFolders.KeePass2AppFolder KeePass2
        {
            get { return _keepass2; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class KeePassTestSuiteRepositoryFolders
    {
        /// <summary>
        /// The LogInAppFolder folder.
        /// </summary>
        [RepositoryFolder("93269426-4e2d-4251-b500-04dc1535117a")]
        public partial class LogInAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _masterpasswordInfo;
            RepoItemInfo _btokInfo;

            /// <summary>
            /// Creates a new LogIn  folder.
            /// </summary>
            public LogInAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LogIn", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, false, "93269426-4e2d-4251-b500-04dc1535117a", "")
            {
                _masterpasswordInfo = new RepoItemInfo(this, "MasterPassword", "text[@controlname='m_tbPassword']/text[@accessiblerole='Text']", "", 10000, null, "982d26ce-9282-492b-9795-a6ecf745d931");
                _btokInfo = new RepoItemInfo(this, "BtOK", "button[@controlname='m_btnOK']", "", 10000, null, "1c9d14c1-7d13-4526-9e9b-f5627600e539");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("93269426-4e2d-4251-b500-04dc1535117a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("93269426-4e2d-4251-b500-04dc1535117a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MasterPassword item.
            /// </summary>
            [RepositoryItem("982d26ce-9282-492b-9795-a6ecf745d931")]
            public virtual Ranorex.Text MasterPassword
            {
                get
                {
                    return _masterpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MasterPassword item info.
            /// </summary>
            [RepositoryItemInfo("982d26ce-9282-492b-9795-a6ecf745d931")]
            public virtual RepoItemInfo MasterPasswordInfo
            {
                get
                {
                    return _masterpasswordInfo;
                }
            }

            /// <summary>
            /// The BtOK item.
            /// </summary>
            [RepositoryItem("1c9d14c1-7d13-4526-9e9b-f5627600e539")]
            public virtual Ranorex.Button BtOK
            {
                get
                {
                    return _btokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtOK item info.
            /// </summary>
            [RepositoryItemInfo("1c9d14c1-7d13-4526-9e9b-f5627600e539")]
            public virtual RepoItemInfo BtOKInfo
            {
                get
                {
                    return _btokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("ad974edd-95b8-413f-81d1-04a1248ba54a")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            KeePassTestSuiteRepositoryFolders.ButtonsFolder _buttons;
            KeePassTestSuiteRepositoryFolders.CategoriesFolder _categories;
            RepoItemInfo _editInfo;
            RepoItemInfo _entryInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, false, "ad974edd-95b8-413f-81d1-04a1248ba54a", "")
            {
                _buttons = new KeePassTestSuiteRepositoryFolders.ButtonsFolder(this);
                _categories = new KeePassTestSuiteRepositoryFolders.CategoriesFolder(this);
                _editInfo = new RepoItemInfo(this, "Edit", "menubar[@controlname='m_menuMain']/menuitem[@name='Entry']", "", 30000, null, "587a67fc-a70b-4225-9f82-9feb72f6688f");
                _entryInfo = new RepoItemInfo(this, "Entry", "container[@controlname='m_splitHorizontal']/?/?/container[@controlname='m_splitVertical']/?/?/table[@controlname='m_lvEntries']/?/?/cell[@text=$vartitle]", "", 10000, null, "2c816f84-4f8b-4db1-ac5c-60ac4e2a16a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ad974edd-95b8-413f-81d1-04a1248ba54a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ad974edd-95b8-413f-81d1-04a1248ba54a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("587a67fc-a70b-4225-9f82-9feb72f6688f")]
            public virtual Ranorex.MenuItem Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("587a67fc-a70b-4225-9f82-9feb72f6688f")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The Entry item.
            /// </summary>
            [RepositoryItem("2c816f84-4f8b-4db1-ac5c-60ac4e2a16a1")]
            public virtual Ranorex.Cell Entry
            {
                get
                {
                    return _entryInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Entry item info.
            /// </summary>
            [RepositoryItemInfo("2c816f84-4f8b-4db1-ac5c-60ac4e2a16a1")]
            public virtual RepoItemInfo EntryInfo
            {
                get
                {
                    return _entryInfo;
                }
            }

            /// <summary>
            /// The Buttons folder.
            /// </summary>
            [RepositoryFolder("648bd750-87a1-4ca5-8603-93d6423d26f1")]
            public virtual KeePassTestSuiteRepositoryFolders.ButtonsFolder Buttons
            {
                get { return _buttons; }
            }

            /// <summary>
            /// The Categories folder.
            /// </summary>
            [RepositoryFolder("42ec2b91-1317-47a0-9189-90d4629145e2")]
            public virtual KeePassTestSuiteRepositoryFolders.CategoriesFolder Categories
            {
                get { return _categories; }
            }
        }

        /// <summary>
        /// The ButtonsFolder folder.
        /// </summary>
        [RepositoryFolder("648bd750-87a1-4ca5-8603-93d6423d26f1")]
        public partial class ButtonsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _savedatabaseInfo;

            /// <summary>
            /// Creates a new Buttons  folder.
            /// </summary>
            public ButtonsFolder(RepoGenBaseFolder parentFolder) :
                    base("Buttons", "", parentFolder, 0, null, false, "648bd750-87a1-4ca5-8603-93d6423d26f1", "")
            {
                _savedatabaseInfo = new RepoItemInfo(this, "SaveDatabase", "?/?/button[@accessiblename='Save Database']", "", 30000, null, "b7ad1373-4828-4d6d-8ba7-59d5eac6905e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("648bd750-87a1-4ca5-8603-93d6423d26f1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SaveDatabase item.
            /// </summary>
            [RepositoryItem("b7ad1373-4828-4d6d-8ba7-59d5eac6905e")]
            public virtual Ranorex.Button SaveDatabase
            {
                get
                {
                    return _savedatabaseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveDatabase item info.
            /// </summary>
            [RepositoryItemInfo("b7ad1373-4828-4d6d-8ba7-59d5eac6905e")]
            public virtual RepoItemInfo SaveDatabaseInfo
            {
                get
                {
                    return _savedatabaseInfo;
                }
            }
        }

        /// <summary>
        /// The CategoriesFolder folder.
        /// </summary>
        [RepositoryFolder("42ec2b91-1317-47a0-9189-90d4629145e2")]
        public partial class CategoriesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _categoryranorexInfo;
            RepoItemInfo _newdatabaseInfo;
            RepoItemInfo _recyclebinInfo;

            /// <summary>
            /// Creates a new Categories  folder.
            /// </summary>
            public CategoriesFolder(RepoGenBaseFolder parentFolder) :
                    base("Categories", "container[@controlname='m_splitHorizontal']//tree[@controlname='m_tvGroups']/tree[@accessiblerole='Outline']", parentFolder, 30000, null, false, "42ec2b91-1317-47a0-9189-90d4629145e2", "")
            {
                _categoryranorexInfo = new RepoItemInfo(this, "CategoryRanorex", "?/treeitem[@accessiblename=$varGroupName]", "", 30000, null, "040065ca-fe26-471d-9be4-b21ade5331cc");
                _newdatabaseInfo = new RepoItemInfo(this, "NewDatabase", "treeitem[@accessiblename='NewDatabase']", "", 30000, null, "c17711fe-1861-4f11-8377-0ec7339ff983");
                _recyclebinInfo = new RepoItemInfo(this, "RecycleBin", "?/?/treeitem[@accessiblename='Recycle Bin']", "", 30000, null, "dc869fdd-d696-48c9-a208-2ddab7390268");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("42ec2b91-1317-47a0-9189-90d4629145e2")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42ec2b91-1317-47a0-9189-90d4629145e2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CategoryRanorex item.
            /// </summary>
            [RepositoryItem("040065ca-fe26-471d-9be4-b21ade5331cc")]
            public virtual Ranorex.TreeItem CategoryRanorex
            {
                get
                {
                    return _categoryranorexInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The CategoryRanorex item info.
            /// </summary>
            [RepositoryItemInfo("040065ca-fe26-471d-9be4-b21ade5331cc")]
            public virtual RepoItemInfo CategoryRanorexInfo
            {
                get
                {
                    return _categoryranorexInfo;
                }
            }

            /// <summary>
            /// The NewDatabase item.
            /// </summary>
            [RepositoryItem("c17711fe-1861-4f11-8377-0ec7339ff983")]
            public virtual Ranorex.TreeItem NewDatabase
            {
                get
                {
                    return _newdatabaseInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The NewDatabase item info.
            /// </summary>
            [RepositoryItemInfo("c17711fe-1861-4f11-8377-0ec7339ff983")]
            public virtual RepoItemInfo NewDatabaseInfo
            {
                get
                {
                    return _newdatabaseInfo;
                }
            }

            /// <summary>
            /// The RecycleBin item.
            /// </summary>
            [RepositoryItem("dc869fdd-d696-48c9-a208-2ddab7390268")]
            public virtual Ranorex.TreeItem RecycleBin
            {
                get
                {
                    return _recyclebinInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RecycleBin item info.
            /// </summary>
            [RepositoryItemInfo("dc869fdd-d696-48c9-a208-2ddab7390268")]
            public virtual RepoItemInfo RecycleBinInfo
            {
                get
                {
                    return _recyclebinInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("7f6a0acc-bda2-4507-8279-5c2acdc4ba2a")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addentryInfo;
            RepoItemInfo _selectallInfo;
            RepoItemInfo _mi_expiresInfo;
            RepoItemInfo _deleteentryInfo;
            RepoItemInfo _addgroupInfo;
            RepoItemInfo _deletegroupInfo;
            RepoItemInfo _emptyrecyclebinInfo;
            RepoItemInfo _performautotypeInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/contextmenu[@processname='KeePass']", parentFolder, 30000, null, false, "7f6a0acc-bda2-4507-8279-5c2acdc4ba2a", "")
            {
                _addentryInfo = new RepoItemInfo(this, "AddEntry", "menuitem[@accessiblename='Add Entry...']", "", 10000, null, "d2f8d87a-7ac4-4997-8e3a-c1227535dcef");
                _selectallInfo = new RepoItemInfo(this, "SelectAll", "contextmenu/menuitem[index()=6]", "", 10000, null, "0d1b7d7c-8372-4935-b723-19eb8b766e64");
                _mi_expiresInfo = new RepoItemInfo(this, "MI_Expires", "menuitem[@name=$varexpires]", "", 10000, null, "69ea2302-efb7-45aa-9d79-aadf9beb3ec4");
                _deleteentryInfo = new RepoItemInfo(this, "DeleteEntry", "menuitem[@accessiblename='Delete Entry']", "", 10000, null, "7375672c-26e6-414f-9bd3-2018212d4eb3");
                _addgroupInfo = new RepoItemInfo(this, "AddGroup", "menuitem[@accessiblename='Add Group...']", "", 30000, null, "5b6127e3-ca3e-4c8c-9540-fadaf2308b49");
                _deletegroupInfo = new RepoItemInfo(this, "DeleteGroup", "menuitem[@accessiblename='Delete Group']", "", 30000, null, "9c62e972-637b-457c-b855-7ede60edd502");
                _emptyrecyclebinInfo = new RepoItemInfo(this, "EmptyRecycleBin", "menuitem[@accessiblename='Empty Recycle Bin']", "", 30000, null, "1f013560-846f-4e6a-8950-733a9eb1687b");
                _performautotypeInfo = new RepoItemInfo(this, "PerformAutoType", "menuitem[@accesskey='f']", "", 30000, null, "74000f3f-8a93-4b06-965c-a9656a11586d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7f6a0acc-bda2-4507-8279-5c2acdc4ba2a")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7f6a0acc-bda2-4507-8279-5c2acdc4ba2a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("d2f8d87a-7ac4-4997-8e3a-c1227535dcef")]
            public virtual Ranorex.MenuItem AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("d2f8d87a-7ac4-4997-8e3a-c1227535dcef")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The SelectAll item.
            /// </summary>
            [RepositoryItem("0d1b7d7c-8372-4935-b723-19eb8b766e64")]
            public virtual Ranorex.MenuItem SelectAll
            {
                get
                {
                    return _selectallInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SelectAll item info.
            /// </summary>
            [RepositoryItemInfo("0d1b7d7c-8372-4935-b723-19eb8b766e64")]
            public virtual RepoItemInfo SelectAllInfo
            {
                get
                {
                    return _selectallInfo;
                }
            }

            /// <summary>
            /// The MI_Expires item.
            /// </summary>
            [RepositoryItem("69ea2302-efb7-45aa-9d79-aadf9beb3ec4")]
            public virtual Ranorex.MenuItem MI_Expires
            {
                get
                {
                    return _mi_expiresInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MI_Expires item info.
            /// </summary>
            [RepositoryItemInfo("69ea2302-efb7-45aa-9d79-aadf9beb3ec4")]
            public virtual RepoItemInfo MI_ExpiresInfo
            {
                get
                {
                    return _mi_expiresInfo;
                }
            }

            /// <summary>
            /// The DeleteEntry item.
            /// </summary>
            [RepositoryItem("7375672c-26e6-414f-9bd3-2018212d4eb3")]
            public virtual Ranorex.MenuItem DeleteEntry
            {
                get
                {
                    return _deleteentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DeleteEntry item info.
            /// </summary>
            [RepositoryItemInfo("7375672c-26e6-414f-9bd3-2018212d4eb3")]
            public virtual RepoItemInfo DeleteEntryInfo
            {
                get
                {
                    return _deleteentryInfo;
                }
            }

            /// <summary>
            /// The AddGroup item.
            /// </summary>
            [RepositoryItem("5b6127e3-ca3e-4c8c-9540-fadaf2308b49")]
            public virtual Ranorex.MenuItem AddGroup
            {
                get
                {
                    return _addgroupInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AddGroup item info.
            /// </summary>
            [RepositoryItemInfo("5b6127e3-ca3e-4c8c-9540-fadaf2308b49")]
            public virtual RepoItemInfo AddGroupInfo
            {
                get
                {
                    return _addgroupInfo;
                }
            }

            /// <summary>
            /// The DeleteGroup item.
            /// </summary>
            [RepositoryItem("9c62e972-637b-457c-b855-7ede60edd502")]
            public virtual Ranorex.MenuItem DeleteGroup
            {
                get
                {
                    return _deletegroupInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DeleteGroup item info.
            /// </summary>
            [RepositoryItemInfo("9c62e972-637b-457c-b855-7ede60edd502")]
            public virtual RepoItemInfo DeleteGroupInfo
            {
                get
                {
                    return _deletegroupInfo;
                }
            }

            /// <summary>
            /// The EmptyRecycleBin item.
            /// </summary>
            [RepositoryItem("1f013560-846f-4e6a-8950-733a9eb1687b")]
            public virtual Ranorex.MenuItem EmptyRecycleBin
            {
                get
                {
                    return _emptyrecyclebinInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The EmptyRecycleBin item info.
            /// </summary>
            [RepositoryItemInfo("1f013560-846f-4e6a-8950-733a9eb1687b")]
            public virtual RepoItemInfo EmptyRecycleBinInfo
            {
                get
                {
                    return _emptyrecyclebinInfo;
                }
            }

            /// <summary>
            /// The PerformAutoType item.
            /// </summary>
            [RepositoryItem("74000f3f-8a93-4b06-965c-a9656a11586d")]
            public virtual Ranorex.MenuItem PerformAutoType
            {
                get
                {
                    return _performautotypeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The PerformAutoType item info.
            /// </summary>
            [RepositoryItemInfo("74000f3f-8a93-4b06-965c-a9656a11586d")]
            public virtual RepoItemInfo PerformAutoTypeInfo
            {
                get
                {
                    return _performautotypeInfo;
                }
            }
        }

        /// <summary>
        /// The AddEntryAppFolder folder.
        /// </summary>
        [RepositoryFolder("b88782a2-88f5-440d-8c3d-5d21e45f1f1b")]
        public partial class AddEntryAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _mbtniconInfo;
            RepoItemInfo _mbtnstandardexpiresInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _repeatInfo;
            RepoItemInfo _titleInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _urlInfo;

            /// <summary>
            /// Creates a new AddEntry  folder.
            /// </summary>
            public AddEntryAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddEntry", "/form[@controlname='PwEntryForm']", parentFolder, 30000, null, false, "b88782a2-88f5-440d-8c3d-5d21e45f1f1b", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@controlname='m_btnOK']", "", 10000, null, "3b40fdac-b28f-4ccf-b027-dbad486140bf");
                _mbtniconInfo = new RepoItemInfo(this, "MBtnIcon", "?/?/tabpage[@controlname='m_tabEntry']/button[@controlname='m_btnIcon']", "", 10000, null, "8143a41c-9a6e-47e0-abc3-9e996b116b22");
                _mbtnstandardexpiresInfo = new RepoItemInfo(this, "MBtnStandardExpires", "?/?/tabpage[@controlname='m_tabEntry']/button[@controlname='m_btnStandardExpires']", "", 10000, null, "6bba1054-8751-40b8-b4d9-0466faecb608");
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/tabpage[@controlname='m_tabEntry']/?/?/text[@accessiblename='Password:']", "", 10000, null, "46fece37-dd24-479c-b159-f332f6327554");
                _repeatInfo = new RepoItemInfo(this, "Repeat", "?/?/tabpage[@controlname='m_tabEntry']/?/?/text[@accessiblename='Repeat:']", "", 10000, null, "323cb55f-eb65-414b-acc5-1974063b4a55");
                _titleInfo = new RepoItemInfo(this, "Title", "?/?/tabpage[@controlname='m_tabEntry']/text[@controlname='m_tbTitle']/text[@accessiblerole='Text']", "", 10000, null, "b57031d9-8f1f-44b7-b7bb-12546f5e8819");
                _usernameInfo = new RepoItemInfo(this, "UserName", "?/?/tabpage[@controlname='m_tabEntry']/?/?/text[@accessiblename='User name:']", "", 10000, null, "384ac546-f38e-4dc5-a1d0-308fbcfd48a6");
                _urlInfo = new RepoItemInfo(this, "URL", "?/?/tabpage[@controlname='m_tabEntry']/?/?/text[@accessiblename='URL:']", "", 30000, null, "e3ce4619-e9bd-4ad6-bd50-b0e732af5915");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b88782a2-88f5-440d-8c3d-5d21e45f1f1b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b88782a2-88f5-440d-8c3d-5d21e45f1f1b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("3b40fdac-b28f-4ccf-b027-dbad486140bf")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("3b40fdac-b28f-4ccf-b027-dbad486140bf")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The MBtnIcon item.
            /// </summary>
            [RepositoryItem("8143a41c-9a6e-47e0-abc3-9e996b116b22")]
            public virtual Ranorex.Button MBtnIcon
            {
                get
                {
                    return _mbtniconInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnIcon item info.
            /// </summary>
            [RepositoryItemInfo("8143a41c-9a6e-47e0-abc3-9e996b116b22")]
            public virtual RepoItemInfo MBtnIconInfo
            {
                get
                {
                    return _mbtniconInfo;
                }
            }

            /// <summary>
            /// The MBtnStandardExpires item.
            /// </summary>
            [RepositoryItem("6bba1054-8751-40b8-b4d9-0466faecb608")]
            public virtual Ranorex.Button MBtnStandardExpires
            {
                get
                {
                    return _mbtnstandardexpiresInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnStandardExpires item info.
            /// </summary>
            [RepositoryItemInfo("6bba1054-8751-40b8-b4d9-0466faecb608")]
            public virtual RepoItemInfo MBtnStandardExpiresInfo
            {
                get
                {
                    return _mbtnstandardexpiresInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("46fece37-dd24-479c-b159-f332f6327554")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("46fece37-dd24-479c-b159-f332f6327554")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Repeat item.
            /// </summary>
            [RepositoryItem("323cb55f-eb65-414b-acc5-1974063b4a55")]
            public virtual Ranorex.Text Repeat
            {
                get
                {
                    return _repeatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Repeat item info.
            /// </summary>
            [RepositoryItemInfo("323cb55f-eb65-414b-acc5-1974063b4a55")]
            public virtual RepoItemInfo RepeatInfo
            {
                get
                {
                    return _repeatInfo;
                }
            }

            /// <summary>
            /// The Title item.
            /// </summary>
            [RepositoryItem("b57031d9-8f1f-44b7-b7bb-12546f5e8819")]
            public virtual Ranorex.Text Title
            {
                get
                {
                    return _titleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Title item info.
            /// </summary>
            [RepositoryItemInfo("b57031d9-8f1f-44b7-b7bb-12546f5e8819")]
            public virtual RepoItemInfo TitleInfo
            {
                get
                {
                    return _titleInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("384ac546-f38e-4dc5-a1d0-308fbcfd48a6")]
            public virtual Ranorex.Text UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("384ac546-f38e-4dc5-a1d0-308fbcfd48a6")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The URL item.
            /// </summary>
            [RepositoryItem("e3ce4619-e9bd-4ad6-bd50-b0e732af5915")]
            public virtual Ranorex.Text URL
            {
                get
                {
                    return _urlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The URL item info.
            /// </summary>
            [RepositoryItemInfo("e3ce4619-e9bd-4ad6-bd50-b0e732af5915")]
            public virtual RepoItemInfo URLInfo
            {
                get
                {
                    return _urlInfo;
                }
            }
        }

        /// <summary>
        /// The IconPickerAppFolder folder.
        /// </summary>
        [RepositoryFolder("f165a7fa-478e-496b-9e0c-0d6723f3dc83")]
        public partial class IconPickerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _li_iconInfo;
            RepoItemInfo _buttoncloseInfo;

            /// <summary>
            /// Creates a new IconPicker  folder.
            /// </summary>
            public IconPickerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IconPicker", "/form[@controlname='IconPickerForm']", parentFolder, 30000, null, false, "f165a7fa-478e-496b-9e0c-0d6723f3dc83", "")
            {
                _li_iconInfo = new RepoItemInfo(this, "LI_Icon", "list[@controlname='m_lvIcons']/listitem[@text=$variconindex]", "", 10000, null, "06940638-9380-4a61-850a-fb9cfc2a40a5");
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonClose", "button[@controlname='m_btnOK']", "", 10000, null, "14b6a481-2561-44c4-9cef-0b803eafa0d7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f165a7fa-478e-496b-9e0c-0d6723f3dc83")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f165a7fa-478e-496b-9e0c-0d6723f3dc83")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LI_Icon item.
            /// </summary>
            [RepositoryItem("06940638-9380-4a61-850a-fb9cfc2a40a5")]
            public virtual Ranorex.ListItem LI_Icon
            {
                get
                {
                    return _li_iconInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The LI_Icon item info.
            /// </summary>
            [RepositoryItemInfo("06940638-9380-4a61-850a-fb9cfc2a40a5")]
            public virtual RepoItemInfo LI_IconInfo
            {
                get
                {
                    return _li_iconInfo;
                }
            }

            /// <summary>
            /// The ButtonClose item.
            /// </summary>
            [RepositoryItem("14b6a481-2561-44c4-9cef-0b803eafa0d7")]
            public virtual Ranorex.Button ButtonClose
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonClose item info.
            /// </summary>
            [RepositoryItemInfo("14b6a481-2561-44c4-9cef-0b803eafa0d7")]
            public virtual RepoItemInfo ButtonCloseInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }
        }

        /// <summary>
        /// The KeePass2AppFolder folder.
        /// </summary>
        [RepositoryFolder("eba40eb0-9836-4cdd-950b-f45c7746145d")]
        public partial class KeePass2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttondeleteInfo;

            /// <summary>
            /// Creates a new KeePass2  folder.
            /// </summary>
            public KeePass2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass2", "/form[@title='KeePass' and @processname='KeePass']", parentFolder, 10000, null, true, "eba40eb0-9836-4cdd-950b-f45c7746145d", "")
            {
                _buttondeleteInfo = new RepoItemInfo(this, "ButtonDelete", ".//button[1]", "", 10000, null, "ea5323c6-eee8-471e-bdfd-3793afe556ed");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eba40eb0-9836-4cdd-950b-f45c7746145d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eba40eb0-9836-4cdd-950b-f45c7746145d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonDelete item.
            /// </summary>
            [RepositoryItem("ea5323c6-eee8-471e-bdfd-3793afe556ed")]
            public virtual Ranorex.Button ButtonDelete
            {
                get
                {
                    return _buttondeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonDelete item info.
            /// </summary>
            [RepositoryItemInfo("ea5323c6-eee8-471e-bdfd-3793afe556ed")]
            public virtual RepoItemInfo ButtonDeleteInfo
            {
                get
                {
                    return _buttondeleteInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
