///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CargarImage recording.
    /// </summary>
    [TestModule("03af2677-4416-4393-abb9-7c5220c42ee4", ModuleType.Recording, 1)]
    public partial class CargarImage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest3Repository repository.
        /// </summary>
        public static MyTest3Repository repo = MyTest3Repository.Instance;

        static CargarImage instance = new CargarImage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CargarImage()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CargarImage Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UploadPicture' at 79;12.", repo.ApplicationUnderTest.UploadPictureInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.UploadPicture.Click("79;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrir.SystemItemNameDisplay' at 44;6.", repo.Abrir.SystemItemNameDisplayInfo, new RecordItemIndex(1));
            repo.Abrir.SystemItemNameDisplay.Click("44;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrir.ButtonAbrir' at 39;14.", repo.Abrir.ButtonAbrirInfo, new RecordItemIndex(2));
            repo.Abrir.ButtonAbrir.Click("39;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='C:\\fakepath\\Perro.png') on item 'ApplicationUnderTest.UploadPicture'.", repo.ApplicationUnderTest.UploadPictureInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.UploadPictureInfo, "TagValue", "C:\\fakepath\\Perro.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='C:\\fakepath\\Perro.png') on item 'ApplicationUnderTest.UploadPicture'.", repo.ApplicationUnderTest.UploadPictureInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.UploadPictureInfo, "Value", "C:\\fakepath\\Perro.png");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
