///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fad88684-2603-42ad-83d9-c8ca5650adc9")]
    public partial class MyTest3Repository : RepoGenBaseFolder
    {
        static MyTest3Repository instance = new MyTest3Repository();
        MyTest3RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTest3RepositoryFolders.ExplorerAppFolder _explorer;
        MyTest3RepositoryFolders.DropdownAppFolder _dropdown;
        MyTest3RepositoryFolders.AbrirAppFolder _abrir;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest3Repository element repository.
        /// </summary>
        [RepositoryFolder("fad88684-2603-42ad-83d9-c8ca5650adc9")]
        public static MyTest3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest3Repository() 
            : base("MyTest3Repository", "/", null, 0, false, "fad88684-2603-42ad-83d9-c8ca5650adc9", ".\\RepositoryImages\\MyTest3Repositoryfad88684.rximgres")
        {
            _applicationundertest = new MyTest3RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new MyTest3RepositoryFolders.ExplorerAppFolder(this);
            _dropdown = new MyTest3RepositoryFolders.DropdownAppFolder(this);
            _abrir = new MyTest3RepositoryFolders.AbrirAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fad88684-2603-42ad-83d9-c8ca5650adc9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3eadc4c8-82e7-46a9-ae53-233a041d1c04")]
        public virtual MyTest3RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("96c1cdf1-d7e1-47eb-95d3-00f6691e7d73")]
        public virtual MyTest3RepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("90e8d0aa-173e-43b7-80b0-8c1390e02081")]
        public virtual MyTest3RepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The Abrir folder.
        /// </summary>
        [RepositoryFolder("e7d9b16f-1b2e-457a-a23d-7c693762e036")]
        public virtual MyTest3RepositoryFolders.AbrirAppFolder Abrir
        {
            get { return _abrir; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest3RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3eadc4c8-82e7-46a9-ae53-233a041d1c04")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            MyTest3RepositoryFolders.ReactDatepickerMonthContainer1Folder _reactdatepickermonthcontainer1;
            RepoItemInfo _somebodytagInfo;
            RepoItemInfo _practiceformInfo;
            RepoItemInfo _studentregistrationformInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _useremailInfo;
            RepoItemInfo _maleInfo;
            RepoItemInfo _usernumberInfo;
            RepoItemInfo _dateofbirthinputInfo;
            RepoItemInfo _css1hwfws3subjectsautocompletevaluInfo;
            RepoItemInfo _readingInfo;
            RepoItemInfo _uploadpictureInfo;
            RepoItemInfo _currentaddressInfo;
            RepoItemInfo _css1hwfws3Info;
            RepoItemInfo _rajasthanInfo;
            RepoItemInfo _csstlfeczindicatorcontainerInfo;
            RepoItemInfo _jaiselmerInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='demoqa.com']", parentFolder, 30000, null, false, "3eadc4c8-82e7-46a9-ae53-233a041d1c04", "")
            {
                _reactdatepickermonthcontainer1 = new MyTest3RepositoryFolders.ReactDatepickerMonthContainer1Folder(this);
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body", "body", 30000, null, "564f35d7-84c6-4d35-ad54-e669da80e514");
                _practiceformInfo = new RepoItemInfo(this, "PracticeForm", ".//div[#'app']/div/div/div/div[2]/div[2]/h1[@innertext='Practice Form']", ".//div[#'app']//h1[@innertext='Practice Form']", 30000, null, "9291dc26-64c2-497a-a024-909a559ebcd8");
                _studentregistrationformInfo = new RepoItemInfo(this, "StudentRegistrationForm", ".//div[#'app']/div/div/div/div[2]/div[2]/h5[@innertext='Student Registration Form']", ".//div[#'app']//h5[@innertext='Student Registration Form']", 30000, null, "48e9d1f4-e328-48ec-9c69-6abd70ce33ed");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'firstName']", ".//input[#'firstName']", 30000, null, "549998ea-7f10-4cc1-9d5d-9faa805002a3");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'lastName']", ".//input[#'lastName']", 30000, null, "406f70f3-33a9-49c4-91bb-a5d6d9ff5064");
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'userEmail']", ".//input[#'userEmail']", 30000, null, "24cda774-164f-4bbf-bd02-8015043956d6");
                _maleInfo = new RepoItemInfo(this, "Male", ".//div[#'genterWrapper']//label[@title='']", ".//div[#'genterWrapper']//label[@title='']", 30000, null, "ee6091be-4d85-4c7b-9505-a2e00dccb01f");
                _usernumberInfo = new RepoItemInfo(this, "UserNumber", ".//input[#'userNumber']", ".//input[#'userNumber']", 30000, null, "b68249fe-d011-46b2-af1b-36f091690c8f");
                _dateofbirthinputInfo = new RepoItemInfo(this, "DateOfBirthInput", ".//input[#'dateOfBirthInput']", ".//input[#'dateOfBirthInput']", 30000, null, "9ad0acaf-160b-42c5-bf35-7498571928b7");
                _css1hwfws3subjectsautocompletevaluInfo = new RepoItemInfo(this, "Css1hwfws3SubjectsAutoCompleteValu", ".//div[#'subjectsContainer']/div/div[1]", ".//div[#'subjectsContainer']/div/div[1]", 30000, null, "2716dc6d-af82-424f-9314-ca8a8f9678f0");
                _readingInfo = new RepoItemInfo(this, "Reading", ".//div[#'hobbiesWrapper']//label[@innertext='Reading']", ".//div[#'hobbiesWrapper']//label[@innertext='Reading']", 30000, null, "ab2e44dc-b797-4fb5-81cb-0519739b429e");
                _uploadpictureInfo = new RepoItemInfo(this, "UploadPicture", ".//input[#'uploadPicture']", ".//input[#'uploadPicture']", 30000, null, "836aa537-876b-4632-86e9-7aaa51bf1619");
                _currentaddressInfo = new RepoItemInfo(this, "CurrentAddress", ".//textarea[#'currentAddress']", ".//textarea[#'currentAddress']", 30000, null, "4a4b929c-7b27-4875-b5a9-20dc697f2258");
                _css1hwfws3Info = new RepoItemInfo(this, "Css1hwfws3", ".//div[#'state']/div/div[1]", ".//div[#'state']/div/div[1]", 30000, null, "46b76dcd-65d9-4845-a0c9-7184480b4b2a");
                _rajasthanInfo = new RepoItemInfo(this, "Rajasthan", ".//div[#'state']//div[@innertext='Rajasthan']", ".//div[#'state']//div[@innertext='Rajasthan']", 30000, null, "f5f57635-0564-42a4-901d-7c264eb6c724");
                _csstlfeczindicatorcontainerInfo = new RepoItemInfo(this, "CssTlfeczIndicatorContainer", ".//div[#'city']/div/div[2]/div", ".//div[#'city']/div/div[2]/div", 30000, null, "f15cf221-88eb-45a3-9ddb-a6ce2dd2c1c1");
                _jaiselmerInfo = new RepoItemInfo(this, "Jaiselmer", ".//div[#'city']//div[@innertext='Jaiselmer']", ".//div[#'city']//div[@innertext='Jaiselmer']", 30000, null, "8cbac9c9-1626-433f-891c-a23b61dad608");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//button[#'submit']", ".//button[#'submit']", 30000, null, "4fb35747-1739-48e1-a055-47eee10fc774");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3eadc4c8-82e7-46a9-ae53-233a041d1c04")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3eadc4c8-82e7-46a9-ae53-233a041d1c04")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("564f35d7-84c6-4d35-ad54-e669da80e514")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("564f35d7-84c6-4d35-ad54-e669da80e514")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }

            /// <summary>
            /// The PracticeForm item.
            /// </summary>
            [RepositoryItem("9291dc26-64c2-497a-a024-909a559ebcd8")]
            public virtual Ranorex.H1Tag PracticeForm
            {
                get
                {
                    return _practiceformInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The PracticeForm item info.
            /// </summary>
            [RepositoryItemInfo("9291dc26-64c2-497a-a024-909a559ebcd8")]
            public virtual RepoItemInfo PracticeFormInfo
            {
                get
                {
                    return _practiceformInfo;
                }
            }

            /// <summary>
            /// The StudentRegistrationForm item.
            /// </summary>
            [RepositoryItem("48e9d1f4-e328-48ec-9c69-6abd70ce33ed")]
            public virtual Ranorex.H5Tag StudentRegistrationForm
            {
                get
                {
                    return _studentregistrationformInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The StudentRegistrationForm item info.
            /// </summary>
            [RepositoryItemInfo("48e9d1f4-e328-48ec-9c69-6abd70ce33ed")]
            public virtual RepoItemInfo StudentRegistrationFormInfo
            {
                get
                {
                    return _studentregistrationformInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("549998ea-7f10-4cc1-9d5d-9faa805002a3")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("549998ea-7f10-4cc1-9d5d-9faa805002a3")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("406f70f3-33a9-49c4-91bb-a5d6d9ff5064")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("406f70f3-33a9-49c4-91bb-a5d6d9ff5064")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("24cda774-164f-4bbf-bd02-8015043956d6")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("24cda774-164f-4bbf-bd02-8015043956d6")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The Male item.
            /// </summary>
            [RepositoryItem("ee6091be-4d85-4c7b-9505-a2e00dccb01f")]
            public virtual Ranorex.LabelTag Male
            {
                get
                {
                    return _maleInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The Male item info.
            /// </summary>
            [RepositoryItemInfo("ee6091be-4d85-4c7b-9505-a2e00dccb01f")]
            public virtual RepoItemInfo MaleInfo
            {
                get
                {
                    return _maleInfo;
                }
            }

            /// <summary>
            /// The UserNumber item.
            /// </summary>
            [RepositoryItem("b68249fe-d011-46b2-af1b-36f091690c8f")]
            public virtual Ranorex.InputTag UserNumber
            {
                get
                {
                    return _usernumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserNumber item info.
            /// </summary>
            [RepositoryItemInfo("b68249fe-d011-46b2-af1b-36f091690c8f")]
            public virtual RepoItemInfo UserNumberInfo
            {
                get
                {
                    return _usernumberInfo;
                }
            }

            /// <summary>
            /// The DateOfBirthInput item.
            /// </summary>
            [RepositoryItem("9ad0acaf-160b-42c5-bf35-7498571928b7")]
            public virtual Ranorex.InputTag DateOfBirthInput
            {
                get
                {
                    return _dateofbirthinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DateOfBirthInput item info.
            /// </summary>
            [RepositoryItemInfo("9ad0acaf-160b-42c5-bf35-7498571928b7")]
            public virtual RepoItemInfo DateOfBirthInputInfo
            {
                get
                {
                    return _dateofbirthinputInfo;
                }
            }

            /// <summary>
            /// The Css1hwfws3SubjectsAutoCompleteValu item.
            /// </summary>
            [RepositoryItem("2716dc6d-af82-424f-9314-ca8a8f9678f0")]
            public virtual Ranorex.DivTag Css1hwfws3SubjectsAutoCompleteValu
            {
                get
                {
                    return _css1hwfws3subjectsautocompletevaluInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Css1hwfws3SubjectsAutoCompleteValu item info.
            /// </summary>
            [RepositoryItemInfo("2716dc6d-af82-424f-9314-ca8a8f9678f0")]
            public virtual RepoItemInfo Css1hwfws3SubjectsAutoCompleteValuInfo
            {
                get
                {
                    return _css1hwfws3subjectsautocompletevaluInfo;
                }
            }

            /// <summary>
            /// The Reading item.
            /// </summary>
            [RepositoryItem("ab2e44dc-b797-4fb5-81cb-0519739b429e")]
            public virtual Ranorex.LabelTag Reading
            {
                get
                {
                    return _readingInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The Reading item info.
            /// </summary>
            [RepositoryItemInfo("ab2e44dc-b797-4fb5-81cb-0519739b429e")]
            public virtual RepoItemInfo ReadingInfo
            {
                get
                {
                    return _readingInfo;
                }
            }

            /// <summary>
            /// The UploadPicture item.
            /// </summary>
            [RepositoryItem("836aa537-876b-4632-86e9-7aaa51bf1619")]
            public virtual Ranorex.InputTag UploadPicture
            {
                get
                {
                    return _uploadpictureInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UploadPicture item info.
            /// </summary>
            [RepositoryItemInfo("836aa537-876b-4632-86e9-7aaa51bf1619")]
            public virtual RepoItemInfo UploadPictureInfo
            {
                get
                {
                    return _uploadpictureInfo;
                }
            }

            /// <summary>
            /// The CurrentAddress item.
            /// </summary>
            [RepositoryItem("4a4b929c-7b27-4875-b5a9-20dc697f2258")]
            public virtual Ranorex.TextAreaTag CurrentAddress
            {
                get
                {
                    return _currentaddressInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The CurrentAddress item info.
            /// </summary>
            [RepositoryItemInfo("4a4b929c-7b27-4875-b5a9-20dc697f2258")]
            public virtual RepoItemInfo CurrentAddressInfo
            {
                get
                {
                    return _currentaddressInfo;
                }
            }

            /// <summary>
            /// The Css1hwfws3 item.
            /// </summary>
            [RepositoryItem("46b76dcd-65d9-4845-a0c9-7184480b4b2a")]
            public virtual Ranorex.DivTag Css1hwfws3
            {
                get
                {
                    return _css1hwfws3Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Css1hwfws3 item info.
            /// </summary>
            [RepositoryItemInfo("46b76dcd-65d9-4845-a0c9-7184480b4b2a")]
            public virtual RepoItemInfo Css1hwfws3Info
            {
                get
                {
                    return _css1hwfws3Info;
                }
            }

            /// <summary>
            /// The Rajasthan item.
            /// </summary>
            [RepositoryItem("f5f57635-0564-42a4-901d-7c264eb6c724")]
            public virtual Ranorex.DivTag Rajasthan
            {
                get
                {
                    return _rajasthanInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Rajasthan item info.
            /// </summary>
            [RepositoryItemInfo("f5f57635-0564-42a4-901d-7c264eb6c724")]
            public virtual RepoItemInfo RajasthanInfo
            {
                get
                {
                    return _rajasthanInfo;
                }
            }

            /// <summary>
            /// The CssTlfeczIndicatorContainer item.
            /// </summary>
            [RepositoryItem("f15cf221-88eb-45a3-9ddb-a6ce2dd2c1c1")]
            public virtual Ranorex.DivTag CssTlfeczIndicatorContainer
            {
                get
                {
                    return _csstlfeczindicatorcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CssTlfeczIndicatorContainer item info.
            /// </summary>
            [RepositoryItemInfo("f15cf221-88eb-45a3-9ddb-a6ce2dd2c1c1")]
            public virtual RepoItemInfo CssTlfeczIndicatorContainerInfo
            {
                get
                {
                    return _csstlfeczindicatorcontainerInfo;
                }
            }

            /// <summary>
            /// The Jaiselmer item.
            /// </summary>
            [RepositoryItem("8cbac9c9-1626-433f-891c-a23b61dad608")]
            public virtual Ranorex.DivTag Jaiselmer
            {
                get
                {
                    return _jaiselmerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Jaiselmer item info.
            /// </summary>
            [RepositoryItemInfo("8cbac9c9-1626-433f-891c-a23b61dad608")]
            public virtual RepoItemInfo JaiselmerInfo
            {
                get
                {
                    return _jaiselmerInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("4fb35747-1739-48e1-a055-47eee10fc774")]
            public virtual Ranorex.ButtonTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("4fb35747-1739-48e1-a055-47eee10fc774")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The ReactDatepickerMonthContainer1 folder.
            /// </summary>
            [RepositoryFolder("8f9bd666-55d9-499e-ad6e-929f783d4c79")]
            public virtual MyTest3RepositoryFolders.ReactDatepickerMonthContainer1Folder ReactDatepickerMonthContainer1
            {
                get { return _reactdatepickermonthcontainer1; }
            }
        }

        /// <summary>
        /// The ReactDatepickerMonthContainer1Folder folder.
        /// </summary>
        [RepositoryFolder("8f9bd666-55d9-499e-ad6e-929f783d4c79")]
        public partial class ReactDatepickerMonthContainer1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _reactdatepickermonthcontainerInfo;
            RepoItemInfo _reactdatepickermonthselectInfo;
            RepoItemInfo _reactdatepickeryearselectInfo;
            RepoItemInfo _divtag23Info;
            RepoItemInfo _divtag14Info;

            /// <summary>
            /// Creates a new ReactDatepickerMonthContainer1  folder.
            /// </summary>
            public ReactDatepickerMonthContainer1Folder(RepoGenBaseFolder parentFolder) :
                    base("ReactDatepickerMonthContainer1", ".//div[#'dateOfBirth']/div[2]/div[2]/div/div/div[2]", parentFolder, 30000, null, false, "8f9bd666-55d9-499e-ad6e-929f783d4c79", "")
            {
                _reactdatepickermonthcontainerInfo = new RepoItemInfo(this, "ReactDatepickerMonthContainer", "", "", 30000, null, "bf6df196-39bf-45d3-91c9-a6b3100f9a5e");
                _reactdatepickermonthselectInfo = new RepoItemInfo(this, "ReactDatepickerMonthSelect", "div[1]/div[2]/?/?/select", "", 30000, null, "cfb9b76d-b2c0-4acf-b590-923975b74768");
                _reactdatepickeryearselectInfo = new RepoItemInfo(this, "ReactDatepickerYearSelect", "div[1]/div[2]/div[2]/select", "div[1]/div[2]/div[2]/select", 30000, null, "457bdd19-6c30-4e58-ac27-d18d8230c1eb");
                _divtag23Info = new RepoItemInfo(this, "DivTag23", "div[2]/div[4]/div[@innertext='23']", "", 30000, null, "1e02e23e-3510-4647-96d1-c9c334fea916");
                _divtag14Info = new RepoItemInfo(this, "DivTag14", "div[2]/div[3]/div[@innertext='14']", "", 30000, null, "b61a2209-0388-44a5-99a1-fac57879c225");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8f9bd666-55d9-499e-ad6e-929f783d4c79")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8f9bd666-55d9-499e-ad6e-929f783d4c79")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ReactDatepickerMonthContainer item.
            /// </summary>
            [RepositoryItem("bf6df196-39bf-45d3-91c9-a6b3100f9a5e")]
            public virtual Ranorex.DivTag ReactDatepickerMonthContainer
            {
                get
                {
                    return _reactdatepickermonthcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ReactDatepickerMonthContainer item info.
            /// </summary>
            [RepositoryItemInfo("bf6df196-39bf-45d3-91c9-a6b3100f9a5e")]
            public virtual RepoItemInfo ReactDatepickerMonthContainerInfo
            {
                get
                {
                    return _reactdatepickermonthcontainerInfo;
                }
            }

            /// <summary>
            /// The ReactDatepickerMonthSelect item.
            /// </summary>
            [RepositoryItem("cfb9b76d-b2c0-4acf-b590-923975b74768")]
            public virtual Ranorex.SelectTag ReactDatepickerMonthSelect
            {
                get
                {
                    return _reactdatepickermonthselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ReactDatepickerMonthSelect item info.
            /// </summary>
            [RepositoryItemInfo("cfb9b76d-b2c0-4acf-b590-923975b74768")]
            public virtual RepoItemInfo ReactDatepickerMonthSelectInfo
            {
                get
                {
                    return _reactdatepickermonthselectInfo;
                }
            }

            /// <summary>
            /// The ReactDatepickerYearSelect item.
            /// </summary>
            [RepositoryItem("457bdd19-6c30-4e58-ac27-d18d8230c1eb")]
            public virtual Ranorex.SelectTag ReactDatepickerYearSelect
            {
                get
                {
                    return _reactdatepickeryearselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ReactDatepickerYearSelect item info.
            /// </summary>
            [RepositoryItemInfo("457bdd19-6c30-4e58-ac27-d18d8230c1eb")]
            public virtual RepoItemInfo ReactDatepickerYearSelectInfo
            {
                get
                {
                    return _reactdatepickeryearselectInfo;
                }
            }

            /// <summary>
            /// The DivTag23 item.
            /// </summary>
            [RepositoryItem("1e02e23e-3510-4647-96d1-c9c334fea916")]
            public virtual Ranorex.DivTag DivTag23
            {
                get
                {
                    return _divtag23Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTag23 item info.
            /// </summary>
            [RepositoryItemInfo("1e02e23e-3510-4647-96d1-c9c334fea916")]
            public virtual RepoItemInfo DivTag23Info
            {
                get
                {
                    return _divtag23Info;
                }
            }

            /// <summary>
            /// The DivTag14 item.
            /// </summary>
            [RepositoryItem("b61a2209-0388-44a5-99a1-fac57879c225")]
            public virtual Ranorex.DivTag DivTag14
            {
                get
                {
                    return _divtag14Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTag14 item info.
            /// </summary>
            [RepositoryItemInfo("b61a2209-0388-44a5-99a1-fac57879c225")]
            public virtual RepoItemInfo DivTag14Info
            {
                get
                {
                    return _divtag14Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("96c1cdf1-d7e1-47eb-95d3-00f6691e7d73")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _demoqagooglechromeInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/form[@title='']", parentFolder, 30000, null, true, "96c1cdf1-d7e1-47eb-95d3-00f6691e7d73", "")
            {
                _demoqagooglechromeInfo = new RepoItemInfo(this, "DEMOQAGoogleChrome", "?/?/listitem[@accessiblename='DEMOQA - Google Chrome']", "?/?/listitem[@accessiblename='DEMOQA - Google Chrome']", 30000, null, "8420c118-af09-4ad4-b1c1-b1140b8b4834");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("96c1cdf1-d7e1-47eb-95d3-00f6691e7d73")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("96c1cdf1-d7e1-47eb-95d3-00f6691e7d73")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DEMOQAGoogleChrome item.
            /// </summary>
            [RepositoryItem("8420c118-af09-4ad4-b1c1-b1140b8b4834")]
            public virtual Ranorex.ListItem DEMOQAGoogleChrome
            {
                get
                {
                    return _demoqagooglechromeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The DEMOQAGoogleChrome item info.
            /// </summary>
            [RepositoryItemInfo("8420c118-af09-4ad4-b1c1-b1140b8b4834")]
            public virtual RepoItemInfo DEMOQAGoogleChromeInfo
            {
                get
                {
                    return _demoqagooglechromeInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("90e8d0aa-173e-43b7-80b0-8c1390e02081")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "90e8d0aa-173e-43b7-80b0-8c1390e02081", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("90e8d0aa-173e-43b7-80b0-8c1390e02081")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("90e8d0aa-173e-43b7-80b0-8c1390e02081")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The AbrirAppFolder folder.
        /// </summary>
        [RepositoryFolder("e7d9b16f-1b2e-457a-a23d-7c693762e036")]
        public partial class AbrirAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _buttonabrirInfo;

            /// <summary>
            /// Creates a new Abrir  folder.
            /// </summary>
            public AbrirAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Abrir", "/form[@title='Abrir']", parentFolder, 30000, null, true, "e7d9b16f-1b2e-457a-a23d-7c693762e036", "")
            {
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='DUIViewWndClassName']//container[@automationid='0']/listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", ".//listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", 30000, null, "6957c9a5-e59a-4a39-9b60-4993a000b0a9");
                _buttonabrirInfo = new RepoItemInfo(this, "ButtonAbrir", "button[@text='&Abrir']", "button[@text='&Abrir']", 30000, null, "5d047378-d00f-42d7-84f1-c7d610a917ee");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e7d9b16f-1b2e-457a-a23d-7c693762e036")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e7d9b16f-1b2e-457a-a23d-7c693762e036")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("6957c9a5-e59a-4a39-9b60-4993a000b0a9")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("6957c9a5-e59a-4a39-9b60-4993a000b0a9")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The ButtonAbrir item.
            /// </summary>
            [RepositoryItem("5d047378-d00f-42d7-84f1-c7d610a917ee")]
            public virtual Ranorex.Button ButtonAbrir
            {
                get
                {
                    return _buttonabrirInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAbrir item info.
            /// </summary>
            [RepositoryItemInfo("5d047378-d00f-42d7-84f1-c7d610a917ee")]
            public virtual RepoItemInfo ButtonAbrirInfo
            {
                get
                {
                    return _buttonabrirInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
