///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Objectivies recording.
    /// </summary>
    [TestModule("565c6f53-5286-4c6e-aaad-17c6c846ebb8", ModuleType.Recording, 1)]
    public partial class Objectivies : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest3Repository repository.
        /// </summary>
        public static MyTest3Repository repo = MyTest3Repository.Instance;

        static Objectivies instance = new Objectivies();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Objectivies()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Objectivies Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Css1hwfws3SubjectsAutoCompleteValu' at 76;20.", repo.ApplicationUnderTest.Css1hwfws3SubjectsAutoCompleteValuInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Css1hwfws3SubjectsAutoCompleteValu.Click("76;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Testar' with focus on 'ApplicationUnderTest.Css1hwfws3SubjectsAutoCompleteValu'.", repo.ApplicationUnderTest.Css1hwfws3SubjectsAutoCompleteValuInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Css1hwfws3SubjectsAutoCompleteValu.PressKeys("Testar");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.Reading' at Center.", repo.ApplicationUnderTest.ReadingInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Reading.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Reading' at Center.", repo.ApplicationUnderTest.ReadingInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Reading.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
