///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validacion_Pagina recording.
    /// </summary>
    [TestModule("7ba16bdb-21ed-4ad4-94f0-5e2abfa98a7d", ModuleType.Recording, 1)]
    public partial class Validacion_Pagina : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest3Repository repository.
        /// </summary>
        public static MyTest3Repository repo = MyTest3Repository.Instance;

        static Validacion_Pagina instance = new Validacion_Pagina();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validacion_Pagina()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validacion_Pagina Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PracticeForm' at 436;31.", repo.ApplicationUnderTest.PracticeFormInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.PracticeForm.Click("436;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.PracticeForm'.", repo.ApplicationUnderTest.PracticeFormInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PracticeFormInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Practice Form') on item 'ApplicationUnderTest.PracticeForm'.", repo.ApplicationUnderTest.PracticeFormInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PracticeFormInfo, "InnerText", "Practice Form");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.StudentRegistrationForm' at 157;18.", repo.ApplicationUnderTest.StudentRegistrationFormInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.StudentRegistrationForm.Click("157;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.StudentRegistrationForm'.", repo.ApplicationUnderTest.StudentRegistrationFormInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.StudentRegistrationFormInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Student Registration Form') on item 'ApplicationUnderTest.StudentRegistrationForm'.", repo.ApplicationUnderTest.StudentRegistrationFormInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.StudentRegistrationFormInfo, "InnerText", "Student Registration Form");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
